Updated java to 17

diff --git a/.github/workflows/maven-publish.yml b/.github/workflows/maven-publish.yml
--- a/.github/workflows/maven-publish.yml
+++ b/.github/workflows/maven-publish.yml
@@ -7,6 +7,7 @@ on:
   pull_request:
     branches:
       - main
+      - david-njau-patch
 
 env:
   DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
@@ -28,10 +29,10 @@ jobs:
 
     steps:
       - uses: actions/checkout@v3
-      - name: Set up JDK 11
+      - name: Set up JDK 17
         uses: actions/setup-java@v3
         with:
-          java-version: '11'
+          java-version: '17'
           distribution: 'temurin'
 
       - name: Build with Maven
@@ -58,6 +59,18 @@ jobs:
           key: ${{ env.SSH_PASS }}
           script_stop: true
           script: |
+            if docker ps -a --format '{{.Names}}' | grep -q ${{ env.CONTAINER_NAME }}; then
+              echo "Check 1"
+              docker stop ${{ env.CONTAINER_NAME }}
+              docker rm ${{ env.CONTAINER_NAME }}
+            fi
+            docker pull --quiet ${{ env.IMAGE_NAME }}
+            if [ $? -eq 0 ]; then
+              echo "Docker image ${{ env.IMAGE_NAME }} pulled successfully"
+            else
+              echo "Error: Failed to pull Docker image ${{ env.IMAGE_NAME }}"
+              exit 1
+            fi
             docker run -d --name ${{ env.CONTAINER_NAME }} -p 8090:8090 ${{ env.IMAGE_NAME }}
             docker logout
             sleep 10
